[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"

    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Access-Control-Allow-Origin"
    Content-Type = "application/json, //optional"
    Access-Control-Allow-Methods = "POST, OPTIONS, GET"
    Access-Control-Max-Age = "8640"